title:              Brody Uehara
email:              brodyuehara@gmail.com
description:        Computer Science Student at the University of Hawaii. Currently an AI Research Intern at Oceanit Labratories. Incoming Sales & Trading Intern at Deutsche Bank
author:             Brody Uehara
baseurl:            "brodyu.github.io/"
url:                ""

# Social Profiles
github_username:    brodyu
linkedin_username:  brodyu

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-160596761-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
